<?php
  include_once("index.html");
  include_once("create.html");
  include_once("delete.html");
  include_once("header.html");
  include_once("header2.html");
  include_once("read_all.html");
  include_once("read_single.html");
  include_once("update.html");
?>